### ISSUE TITLE
Add example implementation for supply newdata for time-varying covariates if the model was only fitting on calibration period dataset

### ISSUE THREAD

**Issue by liangzhangsg** [bachmannpatrick/CLVTools#127]
Hello Patrick, thanks for the great CLVTools package! I encounter an issue for supply newdata for time-varying covariates if the model was only fitting on calibration period dataset. The usecase is in practice, I only have the past transaction data and time-varying covariates data when fit the CLVTools model, after fitting the model, when the time-varying covariates data for prediction period is available, I have to supply the newdata for time-varying covariates for performing prediction. I haven't found a document/guide about this process, and tried an example below but failed. Could you kindly help on this issue? Thanks a lot!

```
## example for supply newdata for time-varying covariates
data("apparelTrans")
data("apparelDynCov")

## keep only training data until "09/10/05", without holdout period data
apparelTrans_train = apparelTrans[apparelTrans$Date <= as.Date("09/10/05", "%d/%m/%y"), ]
apparelDynCov_train = apparelDynCov[apparelDynCov$Cov.Date <= as.Date("09/10/05", "%d/%m/%y"), ]

## clv data obj
clv.obj.train <- clvdata(apparelTrans_train, date.format="ymd",
                   time.unit = "week",  
                   name.id = "Id", name.date = "Date", name.price = "Price")

## merge with covar data
clv.dyn.train <- SetDynamicCovariates(clv.data = clv.obj.train, 
                                data.cov.life = apparelDynCov_train,
                                data.cov.trans = apparelDynCov_train,
                                names.cov.life = c("Marketing", "Gender", "Channel"), 
                                names.cov.trans = c("Marketing", "Gender", "Channel"), 
                                name.id = "Id",
                                name.date = "Cov.Date")

## multithread
registerDoFuture() 
plan("multisession")

## take a while
est.pnbd.dyn.train <- pnbd(clv.dyn.train,
                     start.params.model = c(r=1, alpha = 2, s = 1, beta = 2),
                     start.params.life = c(Marketing=0.5, Gender=0.6, Channel=0.4), 
                     start.params.trans = c(Marketing=0.5, Gender=0.6, Channel=0.4))

summary(est.pnbd.dyn.train)
# Fitting period:                               
# Estimation start  2005-01-03   
# Estimation end    2005-10-09   
# Estimation length 39.8571 Weeks
# 
# Coefficients:
#                 Estimate Std. Error  z-val Pr(>|z|)    
# r                1.34270    0.27409  4.899 9.65e-07 ***
# alpha           42.26207   10.03697  4.211 2.55e-05 ***
# s                0.29837    0.13919  2.144 0.032062 *  
# beta             2.88155    4.27094  0.675 0.499875    
# life.Marketing  -0.74631    0.53477 -1.396 0.162846    
# life.Gender     -0.17705    0.79765 -0.222 0.824341    
# life.Channel    -0.50579    0.49897 -1.014 0.310742    
# trans.Marketing  0.43307    0.05466  7.924 2.22e-15 ***
# trans.Gender     1.41604    0.19587  7.229 4.85e-13 ***
# trans.Channel    0.56577    0.15928  3.552 0.000382 ***
#   ---
#   Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Optimization info:                  
# LL     -2815.4404 
# AIC    5650.8808  
# BIC    5686.0954  
# KKT 1  FALSE      
# KKT 2  TRUE       
# fevals 3001.0000  
# Method Nelder-Mead
# 
# Used Options:                     
#   Correlation     FALSE
#   Regularization  FALSE
#   Constraint covs FALSE

## suppose only after some time the holdout period covar data is available
## how to prepare holdout period covar data for prediction?
## try out
newdata = clvdata(apparelDynCov, date.format="ymd",
          time.unit = "week", 
          estimation.split = "2005-10-09",
          name.id = "Id", name.date = "Cov.Date", name.price=NULL)  

newdata <- SetDynamicCovariates(clv.data = newdata, 
                                      data.cov.life = apparelDynCov,
                                      data.cov.trans = apparelDynCov,
                                      names.cov.life = c("Marketing", "Gender", "Channel"), 
                                      names.cov.trans = c("Marketing", "Gender", "Channel"), 
                                      name.id = "Id",
                                      name.date = "Cov.Date")

# predict next 2 weeks  
results.dyn.train <- predict(est.pnbd.dyn.train, prediction.end=2, newdata=newdata)
# Calculating LogLikelihood values for the provided newdata at the estimated parameters.
# Error in Reduce("+", F2.3.vecs) : object 'F2.3.vecs' not found
```

The error message from `predict()` is 
> Calculating LogLikelihood values for the provided newdata at the estimated parameters. Error in Reduce("+", F2.3.vecs) : object 'F2.3.vecs' not found

**Comment by pschil** [comment]
Happy to hear you enjoy using our package :)

Unfortunately, Im not quite sure if I understand your usecase correctly. 
If you want to split your data in a train and test dataset, this can be done by specifying `estimation.end` in clvdata(). The transaction and covariate data only in the calibration period is then used only to fit the model. The holdout data (transaction and covariate data) after the estimation split then serves as the "test" data.


```
## suppose only after some time the holdout period covar data is available
## how to prepare holdout period covar data for prediction?
```
When supplying `newdata` to `predict()`, the coefficients from the already fitted model object are used to predict with the transaction and covariate data that are in `newdata` while the original data the model was fit on is discarded and not used anymore. The `newdata` is still required to have covariate data for all periods, from estimation start (first transaction in newdata) until prediction end (`prediction.end` in `predict()`). Therefore, the dyncov covariate data in a clvdata object may never have any "holes" (missing dyncov data for some periods or Ids).

By the way: You can also supply longer than needed dyncov covariate data when creating the clvdata object.



> Calculating LogLikelihood values for the provided newdata at the estimated parameters. Error in Reduce("+", F2.3.vecs) : object 'F2.3.vecs' not found

I can reproduce this error with your code and this should definitely not happen. For the prediction some intermediate results from the log-likelihood function are needed which are not present when using `newdata`. The LL is therefore calculated once for the estimation period in `newdata`. It looks like something is going wrong when creating covariate "walks" for the case when predicting 2 or less periods with `newdata`. In the previous package versions it was not allowed to predict <2 periods because it requires different math and it looks like I oversaw this case for creating the walks or fitting the LL.

Best
Patrik

**Comment by pschil** [comment]
I could trace this down while debugging. The error lies in how you create the newdata object: 
```
newdata = clvdata(apparelDynCov, date.format="ymd",
          time.unit = "week",
          estimation.split = "2005-10-09",
          name.id = "Id", name.date = "Cov.Date", name.price=NULL)
```
You are creating a clvdata object not from the transactions but from the covariate data.
`newdata = clvdata(apparelDynCov, ...` should instead be `newdata = clvdata(apparelTrans, ...`. Mind that the first parameter in `clvdata()` is actually called `data.transactions`.
With your current approach there is also no price information available because there is no such column in the covariate data so you could only predict DERT but not CLV.

Your code is an (unrealistic) edge-case that has however revealed multiple real bugs (thanks for that!): If all customers have at least 1 transaction in every single period, the LL code currently breaks at multiple places because only 2 walks are created for every customer.

**Comment by liangzhangsg** [comment]
Thanks for your prompt reply! And my pleasure to contribute multiple real bugs :)
I got your point that

> The newdata is still required to have covariate data for all periods, from estimation start (first transaction in newdata) until prediction end (prediction.end in predict()).

So I create a `newdata` clvdata object by supply `data.transactions`, and `apparelDynCov`(contain both training and holdout period), then the issue is solved now on the example dataset!

Let me try explain better about the use case and post a question about it:
Say today I want to build a model based on customer's historical transaction data and forcast customer's transaction in next 2 weeks, as of today, i only have customer's historical transaction, time-varying covariate data, but not for next 2 weeks. Based on my understanding, if i include the time-varying covariate in the model training, to predict for next 2 weeks, i have to supply the time-varying covariate data of next 2 weeks via `newdata`, which is usually not available in real case.

**Question**: is my understanding correct? If yes, is there suitable way in `CLVTools` for above use case if i want to use time-varying covariates in the training period, but not supply them for prediction period? Thanks!

**Comment by mmeierer** [comment]
`Question: is my understanding correct? If yes, is there suitable way in CLVTools for above use case if i want to use time-varying covariates in the training period, but not supply them for prediction period? Thanks!`

Your understanding is correct. Substantially and practically, what you want to do is to create time-invariant features based on the time-varying covariates in the estimation period. Use these new features to train a model with these time-invariant covariates. While the in-sample fit might be not as good as directly using the time-varying features, you basically only care about the out-of-sample fit and this is a different story. 

`Based on my understanding, if i include the time-varying covariate in the model training, to predict for next 2 weeks, i have to supply the time-varying covariate data of next 2 weeks via newdata, which is usually not available in real case.`
Time-varying variables for available for the future if you look at seasonality (e.g. holidays or paydays or birthdays). Further, quite often marketing actions are known for some time in the future. To conclude, the usage of time-varying covariates for predictions of CLV heavily depends on your use case with seasonality being the most important one. 

Please consider that the implemented models have been developed to derive CLV, i.e. rather long-term predictions of customer behavior. If your focus are short-term predictions, there exist many alternatives. However, all alternatives will suffer from the aforementioned issue with regards to time-varying covariates.

**Comment by pschil** [comment]
> Based on my understanding, if i include the time-varying covariate in the model training, to predict for next 2 weeks, i have to supply the time-varying covariate data of next 2 weeks via newdata, which is usually not available in real case.

Not exactly. As Markus' already pointed out they can be available. And also, you don't have to supply them in newdata, you can already set them in the original clvdata object you use to fit the model. 

Say you have customers transactions from 1.1.2015 until today (21. June 2020) and want to predict until 31.12.2020. This requires that you also have dynamic covariate data from 1.1.2015 until 31.12.2020. You first create the clvdata object from the transaction data (2015-today) and then add all the dynamic covariate data from 1.1.2015-31.12.2020 to it with SetDynamicCovariates(). You can then fit pnbd() on it which only uses the transactions until today and predict with the fitted model until 31.12.2020 or any date before. 
An example with fake data:

```
library(lubridate)
library(data.table)
library(CLVTools)
data("apparelTrans")
data("apparelDynCov")

clv.trans <- clvdata(apparelTrans, date.format = "ymd", time.unit = "w")
# Fake cov data that are longer (2006-12-31) than transaction data (2006-07-16)
covs.2006 <- CJ(Id = apparelTrans[, unique(Id)], Cov.Date = seq(from = ymd("2004-12-26"), 
                                                                to = ymd("2006-12-31"), 
                                                                by= "1 week"))
covs.2006[, Marketing:= sample(x = 0:2, size = .N, replace = T)]


clv.trans.2006 <- SetDynamicCovariates(clv.data = clv.trans, 
                                       data.cov.life = covs.2006, data.cov.trans = covs.2006, 
                                       names.cov.life = "Marketing", 
                                       names.cov.trans = "Marketing",
                                       name.date = "Cov.Date")
p.trans <- pnbd(clv.trans.2006)

# Can predict until 31.12.2006 because there are covs until then in the clv.trans.2006 object
predict(object = p.trans, prediction.end = "2006-12-15")

```

If you want to supply them in newdata, you would have to create the newdata object the exact same way as just described but this is not really the usecase for newdata. It is rather used to supply *more covariate data than first thought* / are present in the clvdata object used for fitting. If you initially wanted to predict only until 31.12.2020 but then decide later to predict until 31.12.2023: Instead of again fitting, you just pass a clvdata object will covariates until 31.12.2023 as newdata. 
Example with fake data:

```
# Even longer cov data until 2008
covs.2008 <- CJ(Id = apparelTrans[, unique(Id)], Cov.Date = seq(from = ymd("2004-12-26"), 
                                                                to = ymd("2008-12-31"), 
                                                                by= "1 week"))
covs.2008[, Marketing:= sample(x = 0:2, size = .N, replace = T)]
# Add these covs to the initial nocov (transaction only) clvdata
clv.trans.2008 <- SetDynamicCovariates(clv.data = clv.trans, 
                                       data.cov.life = covs.2008, data.cov.trans = covs.2008, 
                                       names.cov.life = "Marketing", 
                                       names.cov.trans = "Marketing",
                                       name.date = "Cov.Date")

# With the same model fitted on trans and covs until 31-12-2006, can now predict until 31-12-2008 
# because there are covs until then in the newdata object
predict(object = p.trans, newdata = clv.trans.2008, prediction.end = "2008-12-15")

```


Another usecase of newdata is if your data is very large and takes a long time to fit: You can fit it on a representative sample of customers only, and then supply the full dataset as newdata to predict for all customers:

```
# Select all transactions of 50 customers as a sample
apparelTrans_sample = apparelTrans[Id %in% sample(x = unique(Id), size = 50, replace = FALSE)]

clv.sample <- clvdata(apparelTrans_sample, date.format = "ymd", time.unit = "w", estimation.split = "2005-12-31")
clv.sample <- SetDynamicCovariates(clv.data = clv.sample, 
                                   data.cov.life = apparelDynCov, data.cov.trans = apparelDynCov, 
                                   names.cov.life = c("Marketing", "Gender", "Channel"), 
                                   names.cov.trans = c("Marketing", "Gender", "Channel"),
                                   name.date = "Cov.Date")

# Fit model on sample
p.sample <- pnbd(clv.sample)
# Can only predict for customers in the sample
dt.pred.sample <- predict(p.sample)

# Create clvdata with full apparelTrans dataset, not with sample. 
# Same estimation split etc
clv.full <- clvdata(apparelTrans, date.format = "ymd", time.unit = "w", estimation.split = "2005-12-31")
clv.full <- SetDynamicCovariates(clv.data = clv.full, 
                                 data.cov.life = apparelDynCov, data.cov.trans = apparelDynCov, 
                                 names.cov.life = c("Marketing", "Gender", "Channel"), 
                                 names.cov.trans = c("Marketing", "Gender", "Channel"),
                                 name.date = "Cov.Date")

# Use the model parameters fitted on sample to predict on full data
# Can predict for all customers in data
dt.pred.full <- predict(object = p.sample, newdata = clv.full)

```

**Comment by liangzhangsg** [comment]
Thanks a lot Markus and Patrik help me understand the usage of Time-varying variables better! I will close the issue from my side.
