### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by rlumor** [bachmannpatrick/CLVTools#148]
Because of security reasons I am unable to share a reproducible example. I am working on calculating CLTV for all customers who made a purchase in 2019 irrespective of their cohort (date of first purchase), I have about ~ 200M transactions aggregated at the customer, purchase date level. I took a 5% sample for my analysis.

The challenge i am facing is that some customers don't make their first purchase till the end of year there setting the estimation split generates an error. Also, there is the issue of one time purchasers

What will be your advice to dealing with a challenge like this?

**Comment by pschil** [comment]
Not sure if I understand your problem correctly. My understanding: 
You are only using transaction data from 2019. On these you fit a model, presumably pnbd. Unfortunately, there are also other customers which purchased before 2019 but not in 2019 and they also should have a CLV estimate.

There is no solution for this. If the model has never seen your customer in the fitting period, it cannot make a prediction for them. If you fit the model on the customers that purchased in 2019, a CLV estimate can only be derived for the customers which have purchased in 2019.


> "calculating CLTV for all customers who made a purchase in 2019 irrespective of their cohort (date of first purchase)"

Are you doing this because you want to predict CLV only for customers which **you** think are alive?
If yes, you should not be doing this. The CLV prediction in the pnbd() model already includes an estimate for being alive (PAlive) which is based on how long customers have been around, their purchasing frequency etc. Therefore, in order to derive an accurate value for PAlive for a customer (and based on this CLV), it would in most cases be advised to use the customers' whole purchasing history  - from first purchase until now, and not only for a single year. If you feed a single year, the model will "believe" all customers only came alive in this year although in reality some customers have been with you much longer and buying regularly while other customers really only came alive in this one year used for fitting.

See also my answer [here](https://github.com/bachmannpatrick/CLVTools/issues/146#issuecomment-701342865) where I tried to explain why fitting cohort-wise is important and also about zero-repeaters (one time purchasers).


If you still really only want to look at the CLV of customers active in 2019, it would be better to fit the model cohort wise (and on the whole purchasing history available for each customer), then calculate CLV for every customer, and then when you have CLV for every customer, filter out the CLV estimates of the customers that were active in 2019.

**Comment by rlumor** [comment]
Thank you...this is really helpful. it provides the clarity I need moving forward!.

**Comment by pschil** [comment]
You are welcome
