### ISSUE TITLE
Methodological Question: Value of continuous.discount.factor

### ISSUE THREAD

**Issue by sinkRswim** [bachmannpatrick/CLVTools#162]
Hi Everyone. I have weekly transactional level data for 3 years for a large number of customers. I want to find out the CLV of customers, so I can determine how much I can spend to acquire new customers.

I am struggling with the value for continuous discount factor. Here is my dilemma. When I manually calculate CLV (using discounted cash flow, cost of capital 6%) for the three years (without any future projections), I get a value far larger than the value I get from using the CLV model. I use the following statement to set the cost of capital.
 
results1 <- predict(est.pnbd, continuous.discount.factor = 0.055)

Am I doing anything wrong? Given the data is weekly, should I actually be dividing by 52 (=0.001 instead of 0.055)? Please help.

**Comment by pschil** [comment]
There must be misunderstanding about the nature of the models in this package. 
CLV refers to the value of a customer over his/her full lifetime and not only in the period during which they were observed.

All of the models here predict the *residual* CLV **after** the observation period. Hence, how much more they are worth over the unobserved future until they "die", discounted to the estimation end. It is calculated as DERT * mean spending, see for a better understanding also my explanations about the formula for DERT [here](https://github.com/bachmannpatrick/CLVTools/issues/146#issuecomment-696651684). 
Also see here for explanations about the continuous discounting factor: [Link](https://github.com/bachmannpatrick/CLVTools/issues/5#issuecomment-685140822)


> When I manually calculate CLV (using discounted cash flow, cost of capital 6%) for the three years (without any future projections), I get a value far larger than the value I get from using the CLV model.

If i understood you right, that is because the prediction by the model measures something else (the future, residual CLV after the observation period) than what you calculate by hand (the observed transactions).

**Comment by sinkRswim** [comment]
Aha! That makes sense. I did overlook that fact. Thank you for your timely response.
