### ISSUE TITLE
Estimation Failed with NA coefficients

### ISSUE THREAD

**Issue by ZhenoSan** [bachmannpatrick/CLVTools#176]
Hello, thanks for making this awesome packa.ge

I keep getting this error on all the models.

"Warning: Estimation failed with NA coefficients. The returned object contains results but further usage is restricted. You might want to try to fit the model again with method Nelder-Mead (using optimx.args=list(method="Nelder-Mead")) or try different starting values. See examples.
Warning: Hessian could not be derived. Setting all entries to NA."

Not sure how to proceed or debug the problem?

**Comment by bachmannpatrick** [comment]
Hi, 

The model could not be fitted to your data. This can have different causes. Most likely it is a data issue. Have a look at discussion #132.

Best,
Patrick

**Comment by mmeierer** [comment]
@ZhenoSan: Thanks for using CLVTools. To be able to provide help, please follow the general guidelines for asking questions as outlined on SO (https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example). Otherwise, it is really quite difficult to understand what is going on and we can only speculate.
