### ISSUE TITLE
GGompertz/NBD: Faulty conditional expectation

### ISSUE THREAD

**Issue by bachmannpatrick** [bachmannpatrick/CLVTools#206]
Unfortunately, the current formula for the conditional expectation of the GGompertz/NBD model as reported in Bemmaor & Glady (2012) and as implemented in CLVTools is faulty. The current version leads to an overestimation the expected number of future purchases as it does not accurately consider the lifetime process of the customers.

Note: This also affects the DERT (but we currently have no implementation of DERT in CLVTools --> Any pull request are very much welcome!).

Thanks to Jost Adler (University of  Duisburg-Essen) for letting us know about this and sending in the correction below.

The corrected formula for the expected number of future purchases:
![image](https://user-images.githubusercontent.com/5851114/164090342-b1bf8121-bc15-4734-ab14-687c0bdd4863.png)

Cite the respective work (Adler 2022) in the manual.

**Comment by bachmannpatrick** [comment]
This is the corresponding comment (Adler 2022):
https://pubsonline.informs.org/doi/10.1287/mnsc.2022.4422

**Comment by pschil** [comment]
I have implemented a first WIP of this on `feature-ggomnbd-jostadler-erratum`. 

It seems however that the inputs for z to Hyp2F1 are problematic. For beta < 1, this results in z<0 for which hyp2F1 is not defined. beta does not have to be restricted to beta>=1, as also can be seen in Table2 of estimated parameters in the original paper.

Likely, it could be that Hyp2F1(1, s, s+1, z) due to its special combinations of inputs could be mathematically simplified to a more stable expression which does not require z to be in [0, 1). Perhaps @JeffNaef could solve this? 
Or does this require a case distinction?

For some datasets like cdnow, the model (nearly) collapse into the Pareto/NBD with beta<1. Consequently, the estimates of PAlive are near identical to the Pareto/NBD. So Im fairly confident that a valid expression for CET should exist also for beta<1.

**Comment by pschil** [comment]
The issues with the hyp2F1 were solved by numerically integrating it. @JeffNaef showed that `hyp2F1[1, s, s+1, z]` simplifies as follows: 

![image](https://github.com/bachmannpatrick/CLVTools/assets/11665059/3625840d-f6a5-4620-b440-2fa278055890)
