### ISSUE TITLE
Add tests to check the correctness of the dyncov expectation and LL functions for special inputs with known outputs.

### ISSUE THREAD

**Issue by mmeierer** [bachmannpatrick/CLVTools#98]

**Comment by pschil** [comment]
For the expectation, the following intermediate results:

If covariates data or gamma=0:
all Ai=0, Ci=0

If covariates data & parameters are the same (or gamma=0):
all Dbar_i == Bbar_i

i=1: always Bbar_i = 0 because (Bbar_i - exp.gX.P) + exp.gX.P * (-d1)
i=1: always Dbar_i = 0 because (Dbar_i - exp.gX.L) + exp.gX.L * (-d_omega)]

**Comment by pschil** [comment]
For the *conditional* expectation

If the covariate data is constant for both processes:
A_i and C_i are the same for all i
Bbar_i=-T*A, where A is the constant A_i
Dbar_i = 0

**Comment by pschil** [comment]
For the LL, the following intermediate identities hold

In case all covariates are the same for all periods (and therefore also for gamm=0 or all cov data=0):
- Akprod=A^x
- BkSum=A*T.call 
- barBi=-A*t_x
- barDi=0 
- DkT=C*T.call
-  a1T=A*T.call
- b1T=T*C
- bkT=T*C

**Comment by pschil** [comment]
Tests for the dyncov CET, LL, and expectation intermediate results were added. So far, 1 minor bug was found in the LL.
